# Generated by Django 5.2.6 on 2025-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_about_bio_contact_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
